/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

/**
 *
 * @author Asus
 */
public class PlantManagementworkers extends javax.swing.JFrame {

    /**
     * Creates new form PlantManagementworkers
     */
    public PlantManagementworkers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        jLabel16.setText("6AM - 1PM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Workers");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 115, 37, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Workshift");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 115, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("PN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 115, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Selery");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 115, 37, -1));

        jLabel6.setText("Sadikul");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 143, -1, -1));

        jLabel7.setText("Korim");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 165, 37, -1));

        jLabel8.setText("Rohim");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 187, 37, -1));

        jLabel9.setText("Jodu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 215, 37, -1));

        jLabel10.setText("Modhu");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 237, 43, -1));

        jLabel11.setText("Sadik");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 259, 43, -1));

        jLabel12.setText("Bahar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 291, 43, -1));

        jLabel13.setText("6AM - 1PM");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 143, -1, -1));

        jLabel14.setText("6AM - 1PM");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 187, -1, -1));

        jLabel15.setText("6AM - 1PM");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 215, -1, -1));

        jLabel17.setText("6AM - 1PM");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 291, -1, -1));

        jLabel18.setText("3PM - 8PM");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 165, -1, -1));

        jLabel19.setText("3PM - 8PM");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 237, -1, -1));

        jLabel20.setText("3PM - 8PM");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 259, -1, -1));

        jLabel21.setText("01000000000");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 143, -1, -1));

        jLabel22.setText("01000000000");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 165, -1, -1));

        jLabel23.setText("01000000000");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 187, -1, -1));

        jLabel24.setText("01000000000");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 215, -1, -1));

        jLabel25.setText("01000000000");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 237, -1, -1));

        jLabel26.setText("01000000000");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 259, -1, -1));

        jLabel27.setText("01000000000");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 287, -1, 24));

        jLabel28.setText("9000");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 143, 43, -1));

        jLabel29.setText("9000");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 187, 43, -1));

        jLabel30.setText("9000");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 215, 43, -1));

        jLabel31.setText("9000");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 291, 43, -1));

        jLabel32.setText("8000");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 165, 43, -1));

        jLabel33.setText("8000");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 259, 43, -1));

        jLabel34.setText("8000");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 43, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantManagementworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantManagementworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantManagementworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantManagementworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantManagementworkers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
